### ISSUE TITLE
regular expression

### ISSUE THREAD

**Issue by chiaramoruzzi** [DataAccess2020/CE2_Moruzzi_Taddei#3]
Hey @Federico00taddei you told me that the regular expression used for Task 3 was correct but I can't manage to make it work. I'll try to fix it and then you can check if it look ok to you :)

**Comment by chiaramoruzzi** [comment]
It should be ok now. Let me know what you think

**Comment by Federico00taddei** [comment]
Hi @chiaramoruzzi thanks for the comment, I fixed it and now it's ok, I have comitted you the final result. Cheers :)
