### ISSUE TITLE
Scraping text

### ISSUE THREAD

**Issue by chiaramoruzzi** [DataAccess2020/CE2_Moruzzi_Taddei#5]
dear @Federico00taddei I'm trying to scrape the main text from all the articles' html files we downloaded but I only can do it one at a time. When I try to do it inside the for loop function I get "error: object not found". Can you fix it? 😢😢😢

**Comment by Federico00taddei** [comment]
Sorry for the late time @chiaramoruzzi , I just commited you the final script with the code (one for all the text/paragraphs for all the post and one for only the first paragraph for the posts). Check it out and let me know! :)

**Comment by chiaramoruzzi** [comment]
perfect! thanks
